### PR TITLE
HS-754108 - Remove i wording

### PR DESCRIPTION
**Pull request by wrandall22**
Do not advertise an unsupported feature.

[Helpscout](https://secure.helpscout.net/conversation/1865144154/754108/)

### CODE REVIEW

**Review by aaronlaib — APPROVED** [review]

**Comment by aaronlaib** [comment]
@wrandall22 looks like amplify is complaining in this app too, similar or different issue from mpdx_web?

**Comment by wrandall22** [comment]
Different, from provisioning step: 
```
Build failed to complete successfully. Reason: [BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image. CannotPullContainerError: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]
```

**Comment by wrandall22** [comment]
Haha, got past that error then ran into the same one you hit in mpdx.

**Comment by wrandall22** [comment]
https://github.com/CruGlobal/cru-terraform/blob/master/applications/campus-contacts/web/amplify.tf#L8-L9

**Comment by aaronlaib** [comment]
> https://github.com/CruGlobal/cru-terraform/blob/master/applications/campus-contacts/web/amplify.tf#L8-L9

Yep, same values we have for mpdx. Wondering if we should have a team/shared account so we don't run into this again

**Comment by aaronlaib** [comment]
> This pull request is automatically being deployed by Amplify Hosting ([learn more](https://aws.amazon.com/amplify/hosting/)).Access this pull request here: https://pr-852.d23um2gb8xlk6n.amplifyapp.com

@wrandall22 that's a good sign!

**Comment by wrandall22** [comment]
This seems to be working in stage. I'll plan to deploy tomorrow morning.

**Pull request merged**
